# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kusyokyuu',
            fields=[
                ('kuid', models.IntegerField(primary_key=True, serialize=False)),
                ('kuname', models.CharField(max_length=30)),
                ('question', models.CharField(max_length=100)),
                ('syutudai', models.IntegerField()),
                ('seihu', models.IntegerField()),
            ],
        ),
    ]
