# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_auto_20180721_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='kusyokyuu',
            name='check',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
