# Generated by Django 2.0.6 on 2018-07-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0003_kusyokyuu_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sisyokyuu',
            fields=[
                ('kuid', models.IntegerField(primary_key=True, serialize=False)),
                ('kuname', models.CharField(max_length=30)),
                ('question1', models.CharField(max_length=100)),
                ('syutudai', models.IntegerField()),
                ('seihu', models.IntegerField()),
                ('check', models.IntegerField()),
            ],
        ),
    ]
