# Generated by Django 2.0.6 on 2018-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0004_sisyokyuu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kusyokyuu',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
