# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_kusyokyuu_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='sisyokyuu',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
